### ISSUE TITLE
Support Redirections

### ISSUE THREAD

**Issue by xorz57** [xorz57/shell#3]
Read more about Redirections [here](https://www.gnu.org/software/bash/manual/html_node/Redirections.html#Redirections).

**Comment by BuzzHari** [comment]
I guess I can add this too.

**Comment by xorz57** [comment]
@BuzzHari OK!

**Comment by BuzzHari** [comment]
Is it alright if I just implement the '>' and '<' operators, because to implement the rest, the parser would just become so big.

**Comment by xorz57** [comment]
@BuzzHari At this point maybe it is better to make a better parser first. I don't know if it will be easy to implement the rest operators if we implement only '<' and '>' now. Thanks again for your previous contribution!!!!!!!!!! 🍻

**Comment by BuzzHari** [comment]
Well..I did ended up implementing some of the operators, like '<', '>', '2>', '2>&1'. 
And, you're right at this point, we do need a better parser. Because right now there's no check for wrongly written commands. I shall create a pull request for this one tho. You can add it, if you like. Thank you!
